### PR TITLE
Added  navigation on a Single Page View

### PR DESCRIPTION
**Pull request by fasaldana**
Modified CSS file for styling
Modified JS file for showing and hiding sections when user click on a nav option

### CODE REVIEW

**Review by er-contreras — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

Felix

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Gambit142 — COMMENTED** [review]
Hi @fasaldana @talgidi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was approved by another code reviewer. I opened a zendesk ticket for it to be resolved from the back end but I would also advise you to send a mail to success@microverse.org if the issue is not solved within a short period. 👍 

Sorry for any inconvenience caused. 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fasaldana** [comment]
Hi @Gambit142, can you help me with this issue?
I submitted this pull request and got it approved, and when I submitted the project it showed me again the "REVIEW PENDING" message, but it was I who submitted and got this project approved.
That is why I merged this pull request.

**Comment by Gambit142** [comment]
Hi @fasaldana, you can send a message to success@microverse.org and explain to them all that happened.

**Comment by fasaldana** [comment]
Thank you, @Gambit142, I'm going to do that

**Pull request merged**
